name: Ad-hoc build
on: push
jobs:
  build:
    runs-on: macos-26
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: brew install swiftformat swiftlint
      - name: Configure
        run: |
          ./Scripts/configure-code-signing
          ./Scripts/configure-version
      - name: Lint
        run: make lint
      - name: Test
        run: make test XCODEBUILD_ARGS="CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= DEVELOPMENT_TEAM="
      - name: Archive
        run: xcodebuild archive -project LinearMouse.xcodeproj -scheme LinearMouse -archivePath build/LinearMouse.xcarchive
      - name: Zip app
        run: ditto -c -k --keepParent build/LinearMouse.xcarchive/Products/Applications/LinearMouse.app build/LinearMouse-adhoc.zip
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: LinearMouse-adhoc
          path: build/LinearMouse-adhoc.zip
          retention-days: 3
